logging.level.org.vialle: DEBUG

ethnode:
  data:
    location: 'U:/Users/Eric/Documents/cryptocurrencies/parity/data'
  keystore:
    location: 'U:/Users/Eric/Documents/cryptocurrencies/parity/data/keys'
  json-rpc:
    endpoint: 'http://localhost:8545'